FLIP for `auth` fields and safe reference downcasting
onflow/flips pull request #54
Opened 2022-12-16 15:42 UTC by dsainati1

This adds a FLIP proposing a Cadence change adding a new `auth` access control modifier, and changing the behavior of `references` to permit safe downcasting.

2023-01-03 20:59 UTC, SupunS commented on cadence/2022-12-14-auth-remodel.md
> +is a superset of `{T1, T2, ... }`, or equivalently `∀T ∈ {T1, T2, ... }, ∃U ∈ {U1, U2, ... }, T = U`.
Does this mean casting from an auth-reference to a non-auth reference would be rejected?
e.g:
```cadence
let r: @R = ...

let authRef = &r as auth &R

let simpleRef = authRef as &R    // <--
```

2023-01-03 20:59 UTC, SupunS commented on cadence/2022-12-14-auth-remodel.md
> +To express this, the `auth` keyword can now be used with similar syntax to that of restricted types: `auth{T1, T2, ...}`, where the `T`s
will the old syntax (i.e: without curly braces) continue to be supported, say for restricted types?

2023-01-03 20:59 UTC, SupunS commented on cadence/2022-12-14-auth-remodel.md
> +they would be able to cast this to `auth{Provider} &{Provider}` and call `withdraw`.
The `auth{T} &{U}` syntax is a bit confusing to me.

My first concern is, in a concrete type (struct/resource) scenario, the reference-taking syntax is `let ref = &r auth &T`, but for a restricted type, the user has to specify the type twice `let ref = &r auth{T} &{T}`. Maybe make the `T` in auth{T} optional if both the types are the same?

The second concern is it is easy to confuse the type of the resulting reference. For eg: `auth{Provider} &{Balance}` made me wonder whether I can (or why I can't) call `withdraw` on the resulting reference.
I don't really have any suggestions for an alternative syntax, but if we can find one/improve this to iron out any potential confusion, that would be great.

2023-01-03 21:13 UTC, turbolent reviewed
Great proposal! 👏 

I read through everything except for the attachments discussion point.

In general this a great proposal, with great user benefits: it improves usability, i.e. working with references; and at the same time also increases safety / reduces accidents / the potential of foot-guns. It would be great to get the proposed changes in 👍 

Maybe: In the alternatives considered, describe the earlier idea to allow implementors of concrete types to specify `auth` for interfaces in the conformance list and compare it to the current proposal:
- The earlier idea had one "decision point"
  - Interface authors did not have to, but also could not specify which functions are auth or not
  - Implementors of concrete types could specify `auth` for interfaces in the conformance list
  - Issuer of references did not have to, but also could not specify which interfaces are auth or not
- The current proposal has a mix of "decision points":
  - Interface authors must determine which functions should be authorized
  - Implementors of concrete types do not have to, but also cannot make any decisions (probably OK)
  - Issuers of references can decide auth restrictions
   
The biggest issue for the proposal is not the proposed changes themselves, but its rollout, i.e. the compatibility problems: interface authors need to change access modifier from `pub` to `auth`, e.g. for `FungibleToken.Provider`. I do not think this is a blocker, but will be a challenge.

The second biggest issue is the effort the implementation effort: The existing reference and restriction rules and their implementation are very complex and need to be removed, the new rules are complex too. As this changes the core primitives of access control, the new implementation must be absolutely secure.

Thank you for adding the discussion points at the end. I quite like the idea mentioned at the end, to issue auth/non-auth references based on path domain.

2023-01-03 21:28 UTC, dsainati1 commented on cadence/2022-12-14-auth-remodel.md
> +is a superset of `{T1, T2, ... }`, or equivalently `∀T ∈ {T1, T2, ... }, ∃U ∈ {U1, U2, ... }, T = U`.
No; the rule described here is only for typing between `auth` references. All `auth` reference types remain subtypes of non-`auth` reference types, so you can upcast your `auth` references to non-`auth` freely still.

2023-01-03 21:30 UTC, dsainati1 commented on cadence/2022-12-14-auth-remodel.md
> +To express this, the `auth` keyword can now be used with similar syntax to that of restricted types: `auth{T1, T2, ...}`, where the `T`s
Ideally the old syntax would become deprecated eventually, as currently the only reasonable way to interpret it is as a reference that is `auth` over the entirety of the referenced type, which in the new model would be a very dangerous behavior to have as a default. What would be the use case for keeping the old `auth` syntax that does not require a restriction set?

2023-01-03 21:42 UTC, dsainati1 commented on cadence/2022-12-14-auth-remodel.md
> +exists for security reasons; it should not be possible for someone with a `&{Balance}` reference to downcast that
It seems likely to me that anybody reading or contributing to a language FLIP for Cadence or Flow is aware of the basic `Balance`, `Vault`, `Provider` and `Receiver` types.

2023-01-03 21:49 UTC, dsainati1 commented on cadence/2022-12-14-auth-remodel.md
> +they would be able to cast this to `auth{Provider} &{Provider}` and call `withdraw`.
I agree the syntax is a little bit confusing; at first glance it seems like you have to specify the type twice (once in the `auth{T}` and once in the `&{T}`, but they are really doing quite different things. I think it is going to be quite rare for users to want to declare a reference value this way, however. In fact, with these changes there is little reason to ever actually create a reference value with anything other than its underlying concrete type: `let ref = &r as auth{Provider} &Vault` makes a lot more sense than `let ref = &r as auth{Provider} &{Provider, Receiver}` given that reference types can now be downcast. The "security" aspect of restricted types is effectively being moved to the `auth` part of the type, while the actual reference type itself is now only being used for interface conformance checking. 

I suspect that if we implemented this change, we would only really see restricted types being used as supertypes; i.e. if I want to write a function that operates over all `Provider`s I would write it as `fun(_ p: {Provider})`.

2023-01-03 21:51 UTC, dsainati1 commented
> The biggest issue for the proposal is not the proposed changes themselves, but its rollout, i.e. the compatibility problems: interface authors need to change access modifier from `pub` to `auth`, e.g. for FungibleToken.Provider. I do not think this is a blocker, but will be a challenge.

Yes, I think this is going to be by far the hardest part of the change; I believe we should evaluate the proposal on its own merits, but I also think that "this is a good idea but it's not feasible to roll out" is also a reasonable stance to take here.

2023-01-03 22:39 UTC, turbolent commented on cadence/2022-12-14-auth-remodel.md
> +is a superset of `{T1, T2, ... }`, or equivalently `∀T ∈ {T1, T2, ... }, ∃U ∈ {U1, U2, ... }, T = U`.
Sounds good! Maybe add this clarification to the proposal

2023-01-03 22:50 UTC, turbolent commented on cadence/2022-12-14-auth-remodel.md
> +they would be able to cast this to `auth{Provider} &{Provider}` and call `withdraw`.
I initially had feedback similar to Supun's, but ended up not posting it, so it's great it came up again: 

Restrictions (`Us` in `&T{Us}`) are not really restrictions anymore, as downcasting is now allowed.

We still might want to express something like `T{Us}` (where `Us` is a set of interfaces) for the case where `T` is `AnyStruct`/`AnyResource`. Maybe we should just make the syntax `{Us}` and call it an "interface set"?

The continued existence of restricted types (`T{Us}`) maybe cause confusion for developers, so maybe we should just get rid of them along the way.

2023-01-03 23:20 UTC, dsainati1 commented on cadence/2022-12-14-auth-remodel.md
> +they would be able to cast this to `auth{Provider} &{Provider}` and call `withdraw`.
Yes I really like this idea; the interface set type makes a lot of sense and is more intuitive than restricted types anyways.

2023-01-04 00:16 UTC, SupunS commented on cadence/2022-12-14-auth-remodel.md
> +they would be able to cast this to `auth{Provider} &{Provider}` and call `withdraw`.
With restricted types gone, `{Us}` sounds more like an 'intersection type' now 😄

2023-01-05 00:14 UTC, turbolent commented on cadence/2022-12-14-auth-remodel.md
> +they would be able to cast this to `auth{Provider} &{Provider}` and call `withdraw`.
Right, `{Us}` has been always pretty much like [TypeScript's intersection types](https://www.typescriptlang.org/docs/handbook/2/objects.html#intersection-types). Swift has [protocol composition](https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#ID282), a similar feature (even uses the same `U1 & U2` syntax as TS), though there such a type is not first class (e.g a variable cannot have such a type)

2023-01-05 00:15 UTC, turbolent commented on cadence/2022-12-14-auth-remodel.md
> +## Alternatives Considered
👌

2023-01-05 00:18 UTC, turbolent commented on cadence/2022-12-14-auth-remodel.md
> +    remove "restriced types" and replace them with a "interface set" or "intersection" type that only contains the `{Us}`.
```suggestion
* After this change, it is unclear whether restricted type would still have a place in the type system of Cadence. Consider that
now, with interface types specified both in the `auth` portion of the reference as well in the actual referenced type, there is an
element of redundancy in a type like `auth{T} &{T}` which is unnecessary. Users will be likely to instead specify reference with something like
`let ref = &r as auth{Provider} &Vault` instead of `let ref = &r as auth{Provider} &{Provider, Receiver}` given that downcasting is now possible.

    Restricted types would now only really be used as "interface sets", rather than restrictions, to specify that that a type should have a certain set
    of functionality; e.g. writing a function that operates over all `Provider` types, for example. We can support this use case without restricted types,
    however, the outside part `T` of the restricted type `T{Us}` is no longer necessary. One improvement we could make as part of this change would be to
    remove "restricted types" and replace them with a "interface set" or "intersection" type that only contains the `{Us}`.
```

2023-01-05 00:23 UTC, dreamsmasher commented on cadence/2022-12-14-auth-remodel.md
> +To express this, the `auth` keyword can now be used with similar syntax to that of restricted types: `auth{T1, T2, ...}`, where the `T`s
sweet, then we can reuse the restricted types syntax when we add algebraic effects 🥲

2023-01-05 00:23 UTC, dreamsmasher commented on cadence/2022-12-14-auth-remodel.md
> +```cadecnce
```suggestion
```cadence
```

2023-01-07 21:04 UTC, bluesign commented
This is a great proposal but how to migrate storage ? Stored capabilities with restricted references for example.

2023-01-09 22:07 UTC, dsainati1 commented
Feedback from @sisyphusSmiling on the new attachments release has identified an attachments use case (in addition to the iteration case we already know about) that would benefit a lot from this new feature. In the demo he is working on, he has an attachment for `INFT`s that manages some data in a struct, and has two functions `getRecord` and `resetRecord` to view and to modify the record struct, respectively.

In his use case, he'd like to be able to call `getRecord` from any reference to the attachment, regardless of whether it was accessed from a reference to the base resource or directly from the base resource. However, he wants to restrict access to `resetRecord` to only the owner of the base resource. Currently this is difficult (or impossible) to do in Cadence, since the way attachments currently work preserves no information about how the attachment was accessed inside of their member functions. With the changes proposed in this FLIP however, `resetRecord` could be declared with an `auth` access modifier: 

```
pub attachment R for NonFungibleToken.INFT {
    pub fun getRecord(): AnyStruct { ... }
    access(auth) fun resetRecord() { ... }
}
```

Then, someone with just a reference to the base `b` would be unable to call `resetRecord`, because `b[R]` would not result in an `auth` reference to `R`. However, if they owned `b` (or if `b` was declared to be `auth` for `INFT`), then `b[R]` would result in an `auth` reference to `R` and thus `resetRecord` would be accessible.

2023-01-10 01:20 UTC, turbolent commented
A possible migration could be:

- Ensure existing capabilities do not become more powerful by flagging all contracts as unusable until updated, with correct `auth` modifiers. Given how many contracts have to be updated anyways, this might not be an actual problem
- Ensure existing capabilities stay usable by converting existing capabilities' reference types to auth references, e.g. `Vault{Provider}` -> `auth{Provider} &Vault`

2023-01-10 08:55 UTC, bluesign commented
As we are moving into a bit of role based security (auth vs non-auth) on resources, maybe as alternative we can also discuss, fully role based access. ( Instead of defining interfaces for each role, we can maybe mark the roles, and get interfaces virtually generated somehow ) 

```
pub attachment R for NonFungibleToken.INFT {
    pub fun getRecord(): AnyStruct { ... }
    access(Admin, GameManager) fun resetRecord() { ... }
}
```

2023-01-10 19:18 UTC, turbolent commented
@bluesign Interesting idea to generalize this
- Would the list be a conjunction or disunction?
- How would a type that allows access to `resetRecord` look like?

2023-01-10 20:20 UTC, sisyphusSmiling commented
@turbolent Maybe this will help answer your second question.

Let's say I create an attachment for all NFTs that looks like:
```
pub attachment RecordRetriever for NonFungibleToken.INFT {
    // Retrieves the record of the base NFT
    pub fun getRecord(): AnyStruct { ... }
    // Reset the record of the NFT in some contract
    pub fun resetRecord() { ... }
}
```

What I want is to enable anyone access to the getter method via the existing attachments API
```
let nftRef: &{NonFungibleToken.INFT} = someCollectionReference.borrowNFT(id: 42)!
nftRef[RecordRetriever]!.getRecord()
```

The problem here is that, with the same reference to the NFT, someone can also call:
```
nftRef[RecordRetriever]!.resetRecord()
```

We would want limit the `resetRecord()` method to only be accessible via `@{NonFungibleToken.INFT}`; however, there isn't currently a way to limit that access.

2023-01-10 20:32 UTC, turbolent commented
@katelynsills Would love to hear your thoughts on this proposal!

2023-01-13 00:24 UTC, katelynsills commented
I should preface this by saying that my comments might not be very helpful for refining this FLIP and moving it forward, since the alternative I prefer is so different. And I don't mean to be a blocker :) But I think my comments might still be helpful for 1) diving into how capability people might think about this, and 2) thinking about developer and auditor user experience.

First, this is a really well-written and clear proposal. I still find types hard to reason about because I'm coming from the Wild West of Javascript, but the examples in the FLIP helped a lot.

**Capabilities and reasoning about access**

One of the main goals of capability-based security is to make access control self-evident and easy to reason about. If you have it, you can use it. And if you don't have it, you can't use it. This isn't always strictly true - sometimes you have _less access_ than expected because access is revoked or rate-limited or otherwise cut off. But you can be nearly 100% sure that the recipient can't get more access than what they were given. In other words, you know that if you give someone X, it's very unlikely that they're going to be able to escalate to getting Y just because you made a small mistake or typo. And they're not going to be able to get Y at all unless Y somehow escapes that particular function/file because you returned it from the function explicitly or exported it from the file. 

Prior to this FLIP, I'd been concerned about access control modifiers generally because they seem to violate capability-based security design. They might seem efficient and clean because they're less code, but I think the supposed efficiently is much harder to reason about because it makes local reasoning impossible. Similar to how GOTO statements make reasoning about code insanely difficult because you have no idea how someone might enter the code, having so many access modifiers that mean different things makes reasoning about who and how someone might get access to something really difficult. If your attacker has X, can they get Y? Hard to tell! 

**Rights amplification**

Rights amplification is, roughly speaking, the capability world's name for escalating access, say from X to Y, where Y is admin access. If you want to get admin access to X, you would take X, combine it with a map that is XtoAdmin, and get the admin object out: `XtoAdmin.get(X)` gives Y. Of course, only the people/code who should have extremely high authority have the map XtoAdmin. 

Dete and I were talking about whether this just a dynamic version of type casting. I'm not sure, but I'm leaning towards this actually being different. The auth reference concept does seem similar to having an XtoAdmin map. But I think there is still an important difference, which is that in the capability community example, the ability to get admin access is embodied in an object, not a person/account. If I can show that XtoAdmin never leaves a piece of code, then I've achieved completely local reasoning. (Local reasoning meaning, I can draw conclusions just by looking at this piece of code, and it doesn't matter what the rest of the system does.) The only way that anyone can ever get access to the admin versions of X is by using one of the functions in the piece of code that uses the XtoAdmin map. And if nothing in that piece of code uses XtoAdmin, then absolutely no one is getting any admin object ever.  

With access control modifiers, it seems like many different people or code can hold the same "thing", and their access depends on who and what they are. That seems like basically identity-based access control, and antithetical to capability-based security. It shouldn't matter whether I'm the owner of a resource or not, or whether a contract created a resource. Anyone who has a direct reference to a resource should be able to do exactly the same things. 

So I guess my questions for this FLIP would be:

1) how easy is it for an attacker to confuse a casual reviewer about what access is being granted? Is it easier with this FLIP or harder?
2) how easy is it to write smart contracts "defensively" as a developer? Can you write contracts that are easy to audit, or are they all equally hard because we have to completely map out how different types could be downcast to each other?
3) Does this FLIP further solidify using access control modifiers? Is there any way we could get rid of them, or is that off the table?

2023-01-13 17:02 UTC, dsainati1 commented
@katelynsills Thank you for the excellent comment. These are excellent points to consider, so I'll try to address them one by one. 

> With access control modifiers, it seems like many different people or code can hold the same "thing", and their access depends on who and what they are.

I think this is true for the more traditional access control modifiers like `priv`, or those like `access(contract)` or `access(account)` that are explicitly based on ownership or code location, but not really for the new `auth` modifier. `auth` access is not determined by which account created the contract, or where the code is located, but solely by the permissions that you have for the resource in question. 

> 1. how easy is it for an attacker to confuse a casual reviewer about what access is being granted? Is it easier with this FLIP or harder?

Part of the motivation for this FLIP was that it was very confusing for reviewers and developers that functions like `withdraw` on `Vault`s had `pub` access; this is clearly a function that needs some kind of access control, and yet it is declared with a modifier that would seem to indicate it is publicly callable by anyone. This FLIP should make it easier for people to reason about access: functions that require permissions to use are now explicitly marked, and it's easy to see at a glance exactly what permissions each reference has to the underlying resource. 

> 2. how easy is it to write smart contracts "defensively" as a developer? Can you write contracts that are easy to audit, or are they all equally hard because we have to completely map out how different types could be downcast to each other?

No, the point of this change is to make it so contract authors *don't* have to worry about downcasting! When you mark a function as `auth` on an interface, you know that only somebody with an `auth` reference to that interface will be able to call it. The person who has that reference can upcast or downcast its type as much as they want, but they will never be able to gain more authorization on it. The set of interfaces specified in the `auth` part of the reference type specifies exactly what set of permissions you have on that reference, regardless of how you cast the type. This should make it easy to write "defensive" contracts, because now instead of worrying about which types you create references with, you only need to worry about which `auth` permissions you grant. 

> 3. Does this FLIP further solidify using access control modifiers? Is there any way we could get rid of them, or is that off the table?

Yes, this does elevate the importance of access control (particularly `auth`) modifiers. I am not convinced this is a negative thing, but regardless of opinions on the matter this does make these modifiers even more important to Cadence than they already were.

2023-01-13 18:36 UTC, bluesign commented
> 1. how easy is it for an attacker to confuse a casual reviewer about what access is being granted? Is it easier with this FLIP or harder?

I think this new version is better, it implies at least some kind of auth is involve

> 2.how easy is it to write smart contracts "defensively" as a developer? Can you write contracts that are easy to audit, or are they all equally hard because we have to completely map out how different types could be downcast to each other?

Most functions will be `access(auth)` I guess. I think there is nothing to map, as implementation overrides interface. 

> 3. Does this FLIP further solidify using access control modifiers? Is there any way we could get rid of them, or is that off the table?

I think if we accept `access(auth)` , there should be no objection to somehow expand this to `access([role])` Making it single dimensional has no sense in my opinion. `access(Admin, GameManager) fun resetRecord() ` can be very good if we can define Roles somehow.

2023-01-13 18:38 UTC, dsainati1 commented
> I think if we accept access(auth) , there should be no objection to somehow expand this to access([role]) Making it single dimensional has no sense in my opinion. access(Admin, GameManager) fun resetRecord()  can be very good if we can define Roles somehow.

Functionally these roles are the same thing as interfaces. If you want someone with `Admin` access to be able to call `resetRecord`, you can make `resetRecord` `auth` in the `Admin` interface; the same would be true for `GameManager`.

2023-01-13 18:40 UTC, bluesign commented
> Functionally these roles are the same thing as interfaces. If you want someone with Admin access to be able to call resetRecord, you can make resetRecord auth in the Admin interface; the same would be true for GameManager.

I don't think it can, how to make this below: 

```
pub attachment R for NonFungibleToken.INFT {
    pub fun getRecord(): AnyStruct { ... }
    access(Admin, GameManager) fun resetRecord() { ... }
    access(Admin) fun someAdminFunc() { ... }
}
```

2023-01-13 18:47 UTC, dsainati1 commented
This should be equivalent to:
```
pub resource interface Admin { 
    auth fun resetRecord()
    auth fun someAdminFunc() {
}
pub resource interface GameManager {
    auth fun resetRecord()
}
pub attachment R for NonFungibleToken.INFT: Admin, GameManager {
    pub fun getRecord(): AnyStruct { ... }
    auth fun resetRecord() { ... }
    auth fun someAdminFunc() { ... }
}
```

2023-01-13 18:51 UTC, bluesign commented
> This should be equivalent to:
> 
> ```
> pub resource interface Admin { 
>     auth fun resetRecord()
>     auth fun someAdminFunc() {
> }
> pub resource interface GameManager {
>     auth fun resetRecord()
> }
> pub attachment R for NonFungibleToken.INFT: Admin, GameManager {
>     pub fun getRecord(): AnyStruct { ... }
>     auth fun resetRecord() { ... }
>     auth fun someAdminFunc() { ... }
> }
> ```

GameManager can call `someAdminFunc` here via downcast to R, is it not?

2023-01-13 18:54 UTC, dsainati1 commented
> GameManager can call someAdminFunc here via downcast to R, is it not?

No; this is the key point of this FLIP: If I have a `auth{GameManager} &R` reference, I cannot call any `Admin` `auth` methods on this, as even though `R`'s type "knows" about those methods, my permission set on this reference does not permit the use of any `auth` methods on `Admin`. I also cannot downcast my permission set to gain more permissions; downcasting can only expand the static type of the reference, not its permissions.

2023-01-13 18:56 UTC, bluesign commented
> > GameManager can call someAdminFunc here via downcast to R, is it not?
> 
> No; this is the key point of this FLIP: If I have a `auth{GameManager} &R` reference, I cannot call any `Admin` `auth` methods on this, as even though `R`'s type "knows" about those methods, my permission set on this reference does not permit the use of any `auth` methods on `Admin`. I also cannot downcast my permission set to gain more permissions; downcasting can only expand the static type of the reference, not its permissions.

Yeah I got it after the moment I posted, couldn't delete fast enough :) 

So when it is downcast it is just expanding with `pub` methods

2023-01-13 18:57 UTC, dsainati1 commented
> So when it is downcast it is just expanding with pub methods 

Yes exactly

2023-01-13 19:10 UTC, bluesign commented
This is great, I totally missed that part. Only thing I really would like to make it more readable, something like this maybe: 

```
pub resource interface Admin { 
    auth fun resetRecord()
    auth fun someAdminFunc() {
}
pub resource interface GameManager {
    auth fun resetRecord()
}
pub attachment R for NonFungibleToken.INFT: Admin, GameManager {
    pub fun getRecord(): AnyStruct { ... }
    auth(Admin, GameManager) fun resetRecord() { ... }
    auth(Admin) fun someAdminFunc() { ... }
}
```
It would be nice to see roles without jumping to interfaces. Actually when we agree this is more readable we can also get rid of interfaces for this use case. 


PS: I just saw @turbolent comment when I scroll back 

> @bluesign Interesting idea to generalize this
Would the list be a conjunction or disunction?
How would a type that allows access to resetRecord look like?

I think disjunction ( any of the roles can have access like interfaces ) 
For second part like this example without the interfaces ( they will be there, just generated from the auth tags automatically )

2023-01-13 19:13 UTC, dsainati1 commented
I don't think we can completely get rid of the interfaces because they are necessary to make the type checking work out, but I think automatically producing interfaces from `auth` tags is a really interesting idea that we should explore further.

2023-01-13 20:53 UTC, dsainati1 commented
> It would be nice to see roles without jumping to interfaces.

One other way we could make this happen is via IDE support; on hover of an `auth` function we could show which interfaces it is associated with.

2023-01-16 10:26 UTC, joshuahannan commented
I think this sounds like a pretty great idea! The migration process also makes me a bit nervous if projects remember to upgrade the other breaking changes, but forget about this one for whatever reason. Though I guess it would probably work in the token standards interfaces to require that users have an auth withdraw method, right? so there would be no way they could not do the upgrade properly?

Also, would there be some way to make a method auth even if an interface specified it as `pub`? I could see some projects wanting deposit to still be private, but if the `Receiver` interface specifies it as `pub`, how could they get around that?

2023-01-16 10:44 UTC, bluesign commented
> Also, would there be some way to make a method auth even if an interface specified it as pub? I could see some projects wanting deposit to still be private, but if the Receiver interface specifies it as pub, how could they get around that?

I think this is against the definition of interface. 

I see auth as something between `pub` and `priv`. So if interface is `auth` you can make it `pub` but not the other way around.

2023-01-16 23:39 UTC, franklywatson commented on cadence/2022-12-14-auth-remodel.md
> +### User Impact
@vishalchangrani for visibility/GTM etc

2023-01-17 14:51 UTC, dsainati1 commented
> Also, would there be some way to make a method auth even if an interface specified it as `pub`? I could see some projects wanting deposit to still be private, but if the `Receiver` interface specifies it as `pub`, how could they get around that?

Yeah as @bluesign said this is kind of incompatible with how interfaces work; if someone wanted to do something like this with an `auth` deposit function they'd probably need to implement some kind of different `AuthReceiver` interface instead of the standard `Receiver`.

2023-01-17 22:33 UTC, katelynsills commented
Re: roles, I'm a little concerned about getting into identity-based access control. Roles through interfaces as discussed above seems fine, though. I guess the distinction is whether the code has a sense of "this account is this role" or whether the code is "this role means having this capability, and this account has this capability". The distinction is important when trying to delegate. Delegating an account-based, identity-based role is painful/impossible.

2023-01-19 22:02 UTC, turbolent commented
I remember that @dete had the idea of deriving facets (e.g. `Provider`, `Receiver`, `Balance` for FT `Vault`) from per-function/field modifiers very early on when we discussed the interface-based faceting we have currently.

The main difference/benefit to the current approach of having to declare an interface for each facet is that it reduces boilerplate and code duplication (e.g. `withdraw` has to be redeclared in `Provider`, exactly how it was already declared in `Vault`)

To me that also means that the per-function/field "role" declarations do not really change anything about how we categorize the access control, it would still be capability-based access control, no?

2023-01-20 18:46 UTC, dsainati1 commented
We had a breakout meeting about this and settled on a few things:

1) Overall while there are some specific details of the design that still need working out, sentiment towards the proposal seems favorable enough to say this is likely to proceed in some form or another. A couple points that need working out:
    * Syntax: the `auth{X} &{Y}` syntax is confusing and might result in confusion about what the type and what the authority specification is on a value. One suggestion is to require the type in the `Y` position to not be a restricted type, like `&Y`, which would also require the support of direct usage of interface types, potentially also removing restricted types from the language entirely. 
    * Roles: The current proposal uses interfaces to assign "roles" or "capabilities" for methods implicitly based on which interfaces the methods are inherited from. Separating interfaces from "roles" might simplify the language and make things easier to understand, but would also further increase the complexity of the change. To evaluate the benefits here, we want to actually try to write some Cadence code under the new designs and compare and contrast. We're looking for volunteers to rewrite some large contracts or standards (e.g. an NFT, or the Vault standard) under both the existing design in the FLIP and a proposed design involving roles as separate language constructs and compare the two. 

2) For rollout, it seems as though there is little interest in adding backwards compatibility for this change, and we'd be okay with breaking all existing contracts to guarantee security after this change. A couple ways we might do this would be to change subtyping such that `auth` methods cannot subtype `pub` methods, so that when the NFT standards are updated to use `auth`, any concrete NFTs implementing them will need to change their implementations to use `auth` in order to type check. An even more extreme option would be to remove support for the `pub` alias for `access(all)`, essentially breaking every single existing contract in order to guarantee nothing is implicitly broken.

2023-01-20 18:59 UTC, bluesign commented
Let me summarize few comments while fresh:

On single auth vs roles discussion; I think we can have something nice like what @turbolent mentioned; not sure if I understood correctly but maybe my idea is a bit different. What if we allow nested interfaces in composites?

Usually interfaces are 2 kinds, one is for your own contracts ( usually targeted to single resource ) and the another one is for implementing standards and interop.

from below example:

```
pub resource interface Administration { 
    auth fun resetRecord()
    auth fun someAdminFunc() {
}
pub resource interface GameManagement {
    auth fun resetRecord()
}
pub resource BluesignsGame: Administration, GameManagement {
    pub fun getRecord(): AnyStruct { ... }
    auth(Administration, GameManagement) fun resetRecord() { ... }
    auth(Administration) fun someAdminFunc() { ... }
}
```

what if we allow something like:

```
pub resource BluesignsGame: Administration {
   pub fun getRecord(): AnyStruct { ... }
   interface Administration { 
      auth fun resetRecord(){
          // implementation here
      }
      auth fun someAdminFunc() {
          // implementation here
      }
  }
  pub resource interface GameManagement {
      auth fun resetRecord()
  }
}
```

if we will have interface inheritance this can be written as: (also this forces user to think in capability mindset vs role mindset ) 

```
pub resource BluesignsGame {
   pub fun getRecord(): AnyStruct { ... }
   interface GameManagement {
      auth fun resetRecord(){
          // implementation here
      }
  }
  interface Administration: GameManagement { 
      auth fun someAdminFunc() {
          // implementation here
      }
  }
}
```

- This also prevents for example making auth in interface and pub in implementation accidentally. 
- Also it has benefit of making it more verbose when sharing. ( `auth &{BluesignsGame. Administration} &gameObject` ) , when reading code I will instantly know `gameObject` is `BluesignsGame`

2023-01-20 19:13 UTC, bluesign commented
About upgrading on chain contracts;

If we can have an opt-out auto update mechanism on breaking changes; I think it will be super nice to recover abandoned contracts. 

There are a lot of contracts on mainnet, but all of them are pretty similar. This will be a one time event. According to https://contractbrowser.com there are 2,725 contracts on the mainnet. If we can auto convert with 95% success rate, rest 100-150 contracts, can be crowdsourced with a good bounty hunt event :)

2023-01-21 00:21 UTC, katelynsills commented
Great meeting today! thank you @dsainati1 for making sure my concerns were surfaced. 

I spent some time today looking for examples, and came back to the realization that it's really the concept of access control modifiers cutting through protective encapsulation in potentially surprising ways that I have issue with. Because of that, I want to withdraw my concerns from this FLIP. As far as I can tell, the FLIP itself looks good, although I'm certainly not an expert with type casting and want to yield to those who are. 

I'll see if I can polish up what I've thought through about access control modifiers, and potentially post it on https://forum.onflow.org/.

2023-01-24 00:01 UTC, dreamsmasher commented on cadence/2022-12-14-auth-remodel.md
> +they would be able to cast this to `auth{Provider} &{Provider}` and call `withdraw`.
+1 for changing restricted types to intersection types. Allowing interfaces in type position (even if they need to be qualified somehow) would obviate the need for a separate `Interface` proxy type, making [Cadence issue #2233](https://github.com/onflow/cadence/issues/2233) trivial to implement

2023-01-24 00:04 UTC, dreamsmasher commented on cadence/2022-12-14-auth-remodel.md
> +they would be able to cast this to `auth{Provider} &{Provider}` and call `withdraw`.
Maybe replacing restricted types with standalone intersection types should be its own FLIP?

2023-02-01 18:24 UTC, dsainati1 commented
We had another breakout meeting on this topic, and we came to the consensus that the `auth` access modifiers for fields and functions should reflect the access they require, and we have taken to calling this access an "entitlement", as per @dete. This would look something like what @bluesign and others have suggested above, so where

```
pub resource interface X { 
    auth fun foo ()
    auth fun bar() 
}
pub resource interface Y {
    auth fun bar()
}
pub resource R: X, Y {
    auth fun foo () { ... }
    auth fun bar() { ... }
```

and the entitlements required for `foo` and `bar` are based on the interfaces that define them, instead the user would specify those entitlements in the declaration of the function like so: 

```
pub resource interface X { 
    auth fun foo ()
    auth fun bar() 
}
pub resource interface Y {
    auth fun bar()
}
pub resource R: X, Y {
    auth(X) fun foo () { ... }
    auth(X, Y) fun bar() { ... }
```

This makes it immediately obvious to an auditor which entitlements have access to which functions; i.e. that an `auth{Y} &R` would be able to call `bar` but not `foo`. 

The orthogonal question that is still unresolved is whether these entitlements should be separate entities in the type language from interfaces. In the above example we would require that the entitlement for `X` in the definition of `foo` exist, because `foo` is declared as `auth` on `X`. However, if we were to separate entitlements from interfaces, we could create custom entitlements to allow customizable permissions that are independent from interfaces, which would remove a confusing duality that exists currently in the language where interfaces function both as a supertype for polymorphism and also as a way to specify what permissions a reference has to an object.

2023-02-01 18:27 UTC, dete commented
Some quick syntax suggestions, assuming we go with making entitlements independent from interfaces:

1. Let's make the "super-entitlement" be called `owner`. I think it makes it clear that you are delegating complete authority (it's also a word that make sense both in the `auth(owner)` and `access(owner)` contexts.
2. Let's use something other than braces for entitlements (`{}`) to minimize confusion with interfaces. I think having the ability to pass a reference with a union of multiple interfaces as the type is actually pretty useful, and using `{}` for a union make sense. Thus, I suggest using parens `()` for entitlements (plus parens are already what we use for the `access` decoration).
3. I recommend we get rid of `pub` as an alias for `access(all)`. Now that we have downcasting (and many functions that were previously `pub` can't be!), I think being explicit about access control in a consistent way outweighs the convenience of saving 8 characters.

Some concrete examples using this suggestion:
```
resource interface Provider {
    entitlement withdraw

    access(withdraw) fun withdraw(amount: UFix64): @Vault {}
}

resource interface Receiver {
    access(all) fun deposit(from: @Vault) {}
}

resource interface Balance {
    access(all) fun balance(): UFix64 {}
}

resource interface Vault: Provider, Receiver, Balance {}

resource FlowVault: FungibleToken.Vault {
    access(FungibleToken.withdraw) fun withdraw(amount: UFix64): @Vault {}
    access(all) fun deposit(from: @Vault) {}
    access(all) fun balance(): UFix64 {}

   access(class) fun internalUtilityFunction(otherVault: auth(FungibleToken.withdraw)& FlowVault) {}
   access(FungibleToken.withdraw) fun withdrawAll(): @Vault {}
}
```

It's worth noting that as I wrote this code it was _very_ tempting to use `owner` instead of `FungibleToken.withdraw` in the last two examples. Also worth noting is that when I did it "right" (with a focus on least-authority), I didn't need `owner` at all in this example. Both of these things really emphasize the point @katelynsills made in our live conversation that having some kind of "wildcard" entitlement could be a trap leading to authority leaks.

Having said that, I don't know how else to handle the case for generic containers, like arrays and dictionaries (and user-defined types that have similarly broad utility). One option is just to tell everyone they shouldn't use `owner`. 😅  The other option is to require a type to declare it self as a generic container in order to use the `owner` entitlement. Basically, a safety switch on the footgun that the programmer needs to flip before they endanger their toes... 😇

2023-02-01 18:53 UTC, dsainati1 commented
I like this syntax a lot as well; declaring entitlements inside interfaces/composites like this makes sense to me. 

> In my first draft, I accidentally used FungibleToken.withdraw instead of FungibleToken.Provider.withdraw as the name of the entitlement. The first one actually feels more natural, and I wonder if allowing (maybe even requiring?) entitlements to be declared at the contract level makes sense? Or is that me trying to save typing while eliminating clarity?

Defining `entitlement`s at the contract level I think would seem to imply that you should be able to use the same `entitlement` in different class hierarchies, like:

```
entitlement MyEntitlement 

interface MyInterface {
    access (MyEntitlement) bar()
}

interface MyUnrelatedInterface {
    access (MyEntitlement) bar()
}
```

I think we discussed in the meeting that this ran contrary to the capability based security and that we probably didn't want entitlements to work like this.

2023-02-01 20:04 UTC, bluesign commented
I have few ideas (Sorry today I couldn't talk much, was in a loud environment)

- I think we need to seperate entitlement and interfaces totally, I would go one step further and interfaces should only declare `auth` but not `entitlement` 

- entitlement should be in the resource scope, so basically with multiple interfaces or even without interface I can create entitlements for that resource. 

- I think contract level entitlement is too complicated and error prone too. 

- and last I would prefer entitlements don't intersect functions. ( one function can have one entitlement ) 

So example from @dsainati1 would be something like:

```cadence
pub resource interface X { 
    auth fun foo()
    auth fun bar() 
}
pub resource interface Y {
    auth fun bar()
}
pub resource R: X, Y {
    auth(A) fun foo() { ... }
    auth(B) fun bar() { ... }
}
```

or maybe better: 


```cadence 
pub resource R: X, Y {
    entitlement A {
        fun foo() { ... }
    }
    entitlement B {
        fun bar() { ... }
    }
    pub fun something() { ... }
}
```

- entitlement scope will be automatically `auth` so no need to mention them again. 
- restriction via interface will be equal to granting some set of entitlements, `R(A+B)={X}` and `R(B)={Y}` 

this will force people to structure not around Roles but Entitlements ( Capabilities )

2023-02-01 20:14 UTC, dsainati1 commented
My concern about separating entitlements so completely from interfaces as you suggest is that it would make it impossible to require that someone implement a function with a specific entitlement, which would seem to be something that we'd want. E.g. in the `Vault` example, we want to require that `Vault`s implement their `withdraw` method in such a way that it conforms to the requirements set out in the `Provider` interface, and in `Provider` we want to be able to specify that this method only should be available to those with a certain elevated level of permission. That is to say, I think any semantics we settle on for entitlements should support something like:

```
resource interface Provider {
    // this forces any implementors of `Provider` to make their `withdraw` require a `withdraw` entitlement
    access(withdraw) fun withdraw(amount: UFix64): @Vault {} 
}
```

That said I really like this block syntax for entitlements as well though, I think it will help people organize code and separate concerns to colocate all the code granted to people with specific permissions like this. I'm less certain that we want to prevent entitlements from overlapping on functions though, which this block syntax would require.

2023-02-01 20:17 UTC, katelynsills commented
(@bluesign commented while I was writing this, I didn't take [that comment thread](https://github.com/onflow/flips/pull/54#issuecomment-1412650869) into account yet. I'll follow up.)

Hmm, I'm torn on whether defining an entitlement at the contract level and using it in different class hierarchies is a good thing or not. Here are some rough thoughts:

Of the main principles behind capability-based security is that you want access "reified" in actual objects as much as possible. You want the access to be derived solely from the object itself. If you can get access because it's a Tuesday or by being a certain someone, or by having access to another object, or being able to grab things from the environment, then all bets are off about being able to easily reason about what code (or who) has access to what. Translating this to Cadence is a little hard, because rather than just "objects", you have Resources and capabilities and interfaces (not bad, just different), but one way to translate this is saying that restricted types (I guess both reference types and capability types? This is where my static typing understanding gets bogged down.) are a way to avoid the overhead of having to create and store separate objects for every new attenuation. That seems ok, although typecasting provides a less than obvious way of getting from one "object" (one specific authority bundle) to another. And the less obvious access is, the harder it is to audit.

But, if I'm understanding the above correctly, I really like that with entitlements, we can separate the downcasting necessary for getting specific info about an NFT in a heterogenous container (increasing specificity, but not authority) from the increasing of authority (getting a different entitlement than what you started with). So that part seems great. It eliminates a pathway by which authority could be accidentally leaked.

What I really don't want is code that says "this person or this account has this entitlement" because that is basically a role-based access control list.

But, can someone transfer entitlements to someone else? For it to be capability-based security, they should be able to. In capability-based security, you want every "bundle of authority" to be a transferable object that could be delegated to someone else, and isn't tightly coupled to identity or account. 

As to whether there is a difference between an entitlement being defined within an interface/composite or outside it (contract-level), I could view the contract-level entitlement as being shorthand for "here's a bundle of authority that I created by taking pieces from other bundles of authority." So it does make sense, but I wish it was reified as a Resource (or capability). A good example of this might be the [Administrator Authority in the exampleToken contract](https://github.com/onflow/flow-ft/blob/4416bbe585629671d00d3acfa6fd8052104dd861/contracts/ExampleToken.cdc#L165). It's reified as a Resource, and that seems right to me. I think even if a contract-level entitlement wasn't entirely wrong, it might lead to an absence of reification.

2023-02-03 16:40 UTC, dsainati1 commented
> Let's make the "super-entitlement" be called owner. I think it makes it clear that you are delegating complete authority (it's also a word that make sense both in the auth(owner) and access(owner) contexts.

I was thinking about this a bit further; I don't think we need a specific name for the "super-entitlement" if we can use pre-existing type names for entitlements. If an interface denotes a specific subset of methods in an entitlement, then it would make sense that the name of the actual type being defined (e.g. `FlowVault` here) would mean the entitlement that has access to everything on the composite, like the "owner".

2023-02-04 00:26 UTC, katelynsills commented
> [and last I would prefer entitlements don't intersect functions. ( one function can have one entitlement )](https://github.com/onflow/flips/pull/54#issuecomment-1412650869)

> [I'm less certain that we want to prevent entitlements from overlapping on functions though, which this block syntax would require.](https://github.com/onflow/flips/pull/54#issuecomment-1412665419)

Yeah, I think you do want a single function to be able to be part of multiple entitlements. For instance, whoever has a Vault object itself (the owner) should be able to check the balance, and someone with a provider should be able to check the balance, and an interested member of the general public should be able to check the balance. So that's three entitlements there.

2023-02-06 16:55 UTC, dsainati1 commented
I took a look at the new FT and NFT standard proposals (https://github.com/onflow/flow-nft/pull/126 and https://github.com/onflow/flow-ft/pull/77), and neither of them really seem to require any entitlements beyond those directly associated with the `Provider`, `Transferor/Transferable` and `MetadataViews.ResolverCollection`. However, I think there is a pretty nice compromise we can settle on that gives us the "best of both worlds here".

If we add support for using existing types (interfaces and composites) as entitlements, this likely supports the majority of use cases off the bat. However, if we encounter any use cases or user requests that require the ability to manually define custom entitlements, we can add this feature in as a non-breaking addition later down the road, to allow users to use custom-defined entitlements in addition to those they can get from interfaces and composites. Because it's not breaking to add this later we can produce the simpler version now and add the additional complexity later only if it becomes necessary.

2023-02-08 18:07 UTC, dsainati1 commented
Had another meeting on this; where we addressed a couple points:

1) It does make sense to allow multiple entitlements to be associated with one entitlement; since if this were not possible it would likely result in people using hacky methods to get around this. E.g. if I had a `foo` that was only associated with an `Admin` entitlement, if I wanted to create a `Fooable` entitlement that could also call `foo`, I might just create an another function called `fooForFooable` that called `foo` in its body in order to get me this functionality without actually thoughtfully restructuring my entitlement hierarchy. 

2) We spent a while discussing how entitlements should be defined and attached to function definitions. We reached a rough consensus that entitlements should not be automatically created from interfaces (or equivalently, that interfaces should not be usable as entitlements), but this introduced a new discussion point: Should entitlements be defined as decorators on function declarations (e.g. `access(Admin) function foo() ... `), or should entitlements be created as lists of functions a la interfaces (e.g. `entitlement Admin { function foo() ... }`)? Or would it be reasonable to require both (an explicit entitlement declaration like an interface as well as a decorated modifier on all the functions with that entitlement)? In the case where we don't decorate functions, how do we declare which entitlements are associated with which composites? What modifier do we use?

2023-02-17 18:08 UTC, dsainati1 commented
Had another meeting about this, with a couple major points:

1) We settled on requiring the entitlements to a function be specified in that function's declaration: i.e. `access(X, Y) fun foo()` to ensure that it is obvious to the reader which entitlements are required to call that function. 

2) We also seemed to come to a consensus (although correct me if I am wrong here) that it would be valuable to declare entitlements like interfaces `entitlement E { ... }`. With the above requirement, there is a bit of redundancy, but this can be mitigated with good IDE tooling that allows generating entitlement definitions from groups of methods, and vice versa. We would enforce that any resources that use an entitlement have their definitions match, but a resource would not need to include every method on an entitlement in its definition. So here:

```
entitlement E {
   fun foo(a: A) {}
   fun bar(b: B) {}
}
resource R {
   access(E) foo(a: A) {}
}
```

to use `E` in its definition, `R` must have all of its `access(E)` functions match their definitions in `E`'s definition. However, it is okay for `R` to only implement `foo` on `E` and not `bar`. 

3) We can delay adding support for defining entitlements in terms of combinations of others (union, intersection, etc) until later as it wouldn't be a breaking change. 

4) Entitlements and interfaces should be checked orthogonally; entitlements should not be inherited from interfaces or vice versa. This is for simplicity of use and implementation.

5) We ended the meeting discussing how entitlements should behave with respect to nested objects. As the proposal exists currently, it would be necessary to define multiple fields that provide different views of a nested object field if the author wishes to provide multiple levels of access to that object. We are discussing potential ways to mitigate this, including potentially parametric entitlements, wherein the entitlement of a field can depend on the entitlement of the enclosing reference.

2023-02-17 18:33 UTC, bluesign commented
```
entitlement E {
   fun foo(a: A) {}
   fun bar(b: B) {}
}
resource R {
   access(E) foo(a: A) {}
}
```
with partial implementation; in this case if I need to call `foo` on `R` in a function, it has to have parameter type: `auth(E) &R` or `Capability<auth(E) &R>` but it feels a bit fragile to me. 

Consider this change on contract:

```
entitlement X {
  fun foo(a: A) {}
}
entitlement E {
   fun foo(a: A) {}
   fun bar(b: B) {}
}
resource R {
   access(X) foo(a: A) {}
   access(E) bar(b: B) {}
}
```

now `Capability<auth(E) &R>.check()` will return `true`. What will happen when I borrow is I will get R with `bar`, but my code will call `foo` 

Sorry if I explained it a bit too complex.

2023-02-17 18:48 UTC, dsainati1 commented
Ah this is a good question. I believe that when the contract is updated to change the access modifier of `foo`, any existing code that uses an `auth(E)` reference to call `foo` will become invalid statically (i.e. in type checking), as now `foo` cannot be called without an `X` authorization. 

This is similar to what would happen if I changed the access of a `pub` field to `priv` in a contract update, for example.

2023-02-17 19:01 UTC, bluesign commented
@dsainati1 I think eventually we would need interfaces for that than. ( not to make system fragile ). something like: `Capability<auth(FT.Provider) &R{FT.Provider}>` right? As they cannot stop implementing the interface. ( if I am correct )

2023-02-17 19:05 UTC, dsainati1 commented
> @dsainati1 I think eventually we would need interfaces for that than. ( not to make system fragile ). Considering some FT example, we need something like: `Capability<auth(FT.Provider) &{FT.Provider}>` right? As they cannot stop implementing the interface. ( if I am correct )

I don't think I see how interfaces are related to this; it seems to be purely an issue of changing an access modifier resulting in people who previously had valid references to your resource no longer being able to do the same things with that reference. In such a case people who had previously handed out `auth(E)` references would need to give out `auth(X)` to everyone who previously had one of the old references.

2023-02-17 19:15 UTC, bluesign commented
I am a bit building up slowly, my English is a bit lacking when describing what I think. 

I meant interfaces and entitlements are totally different ( considering binding contract between 2 parties ). Thinking of composability, we need to use interfaces, so technically I need the following code: (otherwise I can break someone else's contract, so they don't use mine ) 

```
entitlement E {
   fun foo(a: A) {}
   fun bar(b: B) {}
}

interface X {
   access(E) foo(a: A) 
}

resource R: X {
   access(E) foo(a: A) {}
}
```

that kinda means; if I want to change `E` on `foo` on `R`; I also have to change on `X`. But then it will break the binding-contract ( so I can break someone else's contract ) So we need to disallow change in X, which leads to disallowing on R.

2023-02-17 20:05 UTC, dsainati1 commented
> somehow `FungibleToken` contract couldn't break me

I think this has never been the case. The interface author has always been able to break downstream contracts, as the interface contract author can add, delete, or modify any function definition any way they like in a contract update. I don't think we are adding any more breakage on contract update than already exists.

2023-02-17 20:22 UTC, bluesign commented
>if  some `Capability<&{UpstreamContract.Interface}>`, and it has a function `foo` that I call in my contract, the author of `UpstreamContract` can later delete `foo` from their interface and break my code.

how?

2023-02-17 20:35 UTC, bluesign commented
Sorry to ask too much, but somehow I am feeling something missing; 
if I tag `withdraw` with 2 entitlements;  `FungibleToken.Provider` from interface, and `Deniz` from my entitlement. 

`Capability<auth(Deniz) &R>` should not be accepted as  `Capability<auth(FungibleToken.Provider) &{FungibleToken.Provider}>` then right?

2023-02-17 20:39 UTC, dsainati1 commented
To clarify: under the new proposal, `FungibleToken.Provider` would not be a valid entitlement, as entitlements and interfaces are not the same thing. However, if you had two entitlements `A` and `B`, a `Capability<auth(A) &R>` would not be accepted as a `Capability<auth(B) &R>`.

2023-03-08 20:37 UTC, dsainati1 commented
Had another breakout session on this topic today, focusing particularly on how nested objects and attachments should behave with regards to entitlements, and in particular if/how the entitlements on the encapsulating value should propagate to the entitlements on an enclosed resource or attachments. We came to a couple conclusions:

1) We want to walk back our previous idea that entitlements should be pre-declared with all members. This is very onerous on developers in that it forces them to consider all possible use cases for their entitlements, and locks users in to a specific set of fields and functions when they wish to use another developer's entitlements for their own case (this comes up particularly when working with attachments). The use case that was originally supported by pre-declared entitlements (seeing all the functions and fields available on a given entitlement) can be supported via tooling in the IDE. We can instead go back to the previous design where entitlements are just "declared" (given a name and brought into scope) in order to guard against issues like typos, but do not need to predeclare their members. 

2) Nested objects and attachments run into an issue wherein it is difficult in the language to specify the "mapping" between the entitlements on the base value and the entitlements on the nested value. @turbolent's example in https://forum.onflow.org/t/super-user-account/4088/15 is a perfect demonstration of this idea; in order to have the access of the `Contracts` sub-object depend on the access you posses for the overall `Account` object, we need to either specify multiple fields with different views of the same reference, or we need to be able to specify the relationship above. Additionally, because attachments need to be usable without any foreknowledge from the base value's author, this relationship needs to be specifiable entirely by the author of the nested object/attachment. We are going to investigate possibly creating a language construct as part of the entitlements feature to allow users to manually define a mapping that specifies how entitlements propagate between parent and child objects.

2023-04-03 15:21 UTC, dsainati1 commented
After a number of breakout sessions discussing this FLIP, we think we've reached consensus on the major points here. In the next LDM we are going to move to start voting on accepting this FLIP unless there are any further major questions or concerns raised.

2023-04-17 14:26 UTC, dsainati1 commented
While we are in the final phases of discussing this PR, a couple small questions remain to be answered regarding the details of entitlement mappings. 

1) In the current design, entitlement mappings can be declared globally like any other type, and can be used in any type. E.g. the following is permitted:
```
entitlement mapping M {
    X -> Y
}
resource R {
    access(M) fun foo(): auth(M) &T { ... }
}
```
where `R` can have a member declared with `M` access, referencing this global declaration. However, one suggestion we have received is to require that the mappings be used only in the definitions that declare them, requiring the above example to be written as:
```
resource R {
    entitlement mapping M {
        X -> Y
    }
    access(M) fun foo(): auth(M) &T { ... }
}
```
This would mean that mappings could not be re-used across multiple composite definitions. Is this a sensible restriction to impose? Or is there a use case for reusing these mappings?

2) In the current design, all mappings have an implicit `pub -> pub` relationship. This means that given a definition like 
```
entitlement mapping M {
    X -> Y
}
resource R {
    access(M) fun foo(): auth(M) &T { ... }
}
```
If you were to call `foo()` on a value of type `auth(X) &R`, you would get a result of `auth(Y) &T` as defined. However, if you were to call `foo()` on a value of type `&R` with no authorization, you would get a regular `&T` result, as `pub` authorization implicitly passes through maps unchanged. Additionally, were you to call `foo()` on a value of type `auth(Z) &R`, the result would also be an unauthorized `&T` value, as `Z` is not a valid input to the map. 

One potential change that could be made here would be to statically reject accesses to mapped-access members that are not made with at least one entitlement that was a valid input to the map. So unless an explicit `pub -> T` mapping were added to the mapping, a mapped member could not be accessed on an unauthorized reference. Similarly, unless `T` were a valid input to the map, a mapped member could not be accessed on a `T`-authorized reference. 

The benefit of this is that the mapping behavior is more explicit, while the downside is that the behavior is less clear in cases where a reference possesses multiple entitlements. In the above-defined mapping `M` it is clear what would happen if an `M`-mapped field were accessed on a reference entitled to both `X` and `Z`; `X` maps to `Y` while `Z` is unmapped and so produces `pub`. However, in a design where an access on a `Z`-entitled reference would be rejected, it is unclear what the behavior should be when the mapped member is accessed on a reference entitled to both `X` and `Z`.

2023-04-25 21:11 UTC, dsainati1 commented
@bluesign @sisyphusSmiling I wanted your thoughts on a potential change to this FLIP, as you've participated in past discussion and have had good feedback from a smart-contract developer perspective:

@dete raise a concern during some internal discussion that it is too easy to accidentally grant someone too many entitlements to a reference without realizing. In particular code like this:

```
fun foo(): auth(X) &T {
   return &myTValue as auth(X, Y) &T
}
```

Would give out a reference that is statically typed as `auth(X) &T`, but dynamically typed as `auth(X, Y) &T`. This means the reference could later be downcast back to its dynamic type, which may not be what the author of `foo` intended or expected. In our experience developers expect the dynamic type of a value to be upcast along with the static type in cases like this. 

Dete proposed that we remove the dynamic part of entitlements and make them a static-only component of a reference type, the implication of this being that it would no longer be possible to gain more entitlements on a downcast. This would prevent the security footgun above, but would prevent use cases where users try to dynamically do different things with a value depending on which entitlements they possess to it, as these entitlements would only be exist at type-checking time. In particular this would hamper potential iteration use cases; e.g. if someone wrote an `fun iterate(nft: &{NFT})` function to iterate over their NFT collection, it would not be possible to do anything with these `NFT`s other than what is possible with public access, as it would be impossible to downcast the `nft` reference parameter to gain more entitlements (note that it is still possible to downcast `nft` to a more concrete type). 

Is this restriction too burdensome/limiting for the security benefits it provides, in your opinions?

2023-04-26 18:23 UTC, sisyphusSmiling commented
@dsainati1 My immediate follow up question is whether we can mitigate occurrences of excess entitlement grants by other means. Perhaps this is a naive attempt to have the best of both worlds, but I'm thinking something like a warning in an IDE informing a developer they're returning `auth(X, Y) &T` in a method expecting `auth(X) &T`.

In the event the compromise is not preferable, I would want to balance the iteration use case you mentioned with plans for [attachment iteration](https://github.com/onflow/cadence/issues/2193). Would removing the dynamic part of entitlements overly restrict the potential usefulness of attachment iteration?

cc: @joshuahannan @satyamakgec

2023-04-26 18:25 UTC, dsainati1 commented
> Would removing the dynamic part of entitlements overly restrict the potential usefulness of attachment iteration?

As far as I can tell (although someone please chime in if you have an idea to get around this problem) is that the functional implication of this would be that only `pub` methods and fields on attachments would be available during iteration. If you want to access an entitlement-restricted field on an attachment you would need to instead access the entitlement explicitly.

2023-04-27 15:17 UTC, sisyphusSmiling commented
> In our experience developers expect the dynamic type of a value to be upcast along with the static type in cases like this.

Agreed on this front. Bear with me while I think through the following case with existing access controls:

```
pub fun getB(): &R{B} {
    return self.account.getCapability(/public/R).borrow<&R>()!
}
```

Where resource `R` implements interfaces `A` and `B` and a statically typed reference of `&R` is returned as a restricted type `&R{B}`. The returned value is restricted as the statically declared return Type, and cannot be cast as `&R{A, B}` even though the return value is statically typed as `&R` within the function scope.

While dealing with different constructs - interfaces vs. entitlements - the case with existing controls on access delegation feels similar.

That's all to say that I think removing the dynamic typing maps to existing developer expectations and contract authoring patterns, and the stronger security gained by the removal of dynamic part of entitlements is worth the cost.

Curious to know hear what other folks think here as well.

2023-04-27 17:07 UTC, dsainati1 commented
> However, one suggestion we have received is to require that the mappings be used only in the definitions that declare them

Regarding this proposed example above, after considering this and starting work on a prototype for it, I realized that allowing entitlement mappings to be declared inside structs and resources necessitates the question of how these values are inherited from interfaces and how conformance checks work for them. This introduces unnecessary complexity with unclear benefit, so unless there is a compelling reason to do otherwise I am going to opt against this proposed change.

2023-05-02 00:00 UTC, dete requested changes

2023-05-02 00:00 UTC, dete commented on cadence/2022-12-14-auth-remodel.md
> +An entitlement list defined using a `,` functions like a conjunction set (or an "and"); it is accessible only to an `auth` reference with all of those entitlements.
I feel like this section should have some note on precedence (eg. How do we interpret `auth(A, B | C)`.) FWIW- My suggestion is that any mix of AND and OR operators must include parens for precedence (making my example a syntax error that would _require_ the author to explicitly write `auth((A, B) | C)` or `auth(A, (B | C))`.

I also think that `+` would be better than `,` for this: eg. `auth(A+B)` instead of `auth(A,B)`.

2023-05-02 00:00 UTC, dete commented on cadence/2022-12-14-auth-remodel.md
> +that the access rules defined above allow any `access(I)` members to be accessed on it.
A table could be useful here!

| Modifier(s) | Visibility |
|--------|--------|
| `access(self)`, `priv` | Methods defined within the same type object. |
| `access(contract)` | Methods defined within the same smart contract object. |
| `access(account)` | Methods defined in a contract deployed to the same account. |
| `access(owner)` | Code holding the direct object or code holding an `auth(owner)` reference. | 
| `access(X)` | Code holding an `auth(X)` reference for some defined entitlement `X`. | 
| `access(all)`, `pub` | Any code with any reference to the object. |

Note that methods defined within the type can treat any reference to an instance of that type with as though they had an `auth(owner)` reference. (i.e. They can call any method regardless of the access modifiers.)

Note that direct access to the object or an `auth(owner)` reference allows you to get an `auth(X)` reference for _any_ defined entitlement `X`.

2023-05-02 00:00 UTC, dete commented on cadence/2022-12-14-auth-remodel.md
> +```
This is a really odd use-case to include in an example. Resources _mostly_ exist to represent values that can live in storage, but references aren't allowed to be stored. So the code here, while perhaps correct, is not very useful for most Cadence users.

The good news is that this helps motivate the mapping functionality, to be honest! Because you can't have two `let` statements that both point at the same object, you kind of _need_ to have a mapping!

2023-05-02 00:00 UTC, dete commented on cadence/2022-12-14-auth-remodel.md
> +```
Hrm. This might point to a bigger problem. Using references as data members of Resource objects isn't really great for this example, either.

But! It raises a bigger question. If the standard way of storing a Resource inside a Resource is not via a reference, what happens here:

```
resource R {
    access(all) let inner: auth(X) @SomeType

   access(all) fun typeFun() {
      self.inner   // what is the type of this statement?
   }
}

fun test(r: &R) {
   r.inner  // What is the type of this statement?
}
```

You'd think that `self.inner` would be type `@SomeType`. And, intuitively, I would say that `r.inner` would be of type `auth(X) &SomeType`. But why is one a reference and one direct access? Could we say that `self.inner` is actually `auth(owner) &SomeType` instead(at least, when used as an r-value)?

2023-05-02 00:00 UTC, dete commented on cadence/2022-12-14-auth-remodel.md
> +the owner of the inner resource.
I think this Flip should include a minimal set of entitlements for the built-in containers, and this would be a great time to include a concrete example of how they could be used, which I think would motivate the reader to better understand the power of mappings.

So, assume that we have `Insert`, `Replace`, and `Remote` entitlements for the built-in dictionary types. A neat example of using mappings would be something like this:
```
entitlement mapping UserListUpdates {
  AddUser -> Insert
  RemoveUser -> Remove
  UpdateUser -> Replace
  all -> all
}

access (UserListUpdates) let userList: auth(UserListUpdates) userList{String: UserData}
```

2023-05-02 00:00 UTC, dete commented on cadence/2022-12-14-auth-remodel.md
> +```
I'll be honest. I would love to remove or at least deprecate `pub` and `priv`. If this code examples (for example) used `access(self)` and `access(all)` it'd be easier to parse (visually, as a human) and more consistent.

```cadence
pub resource R {
    access(E) fun foo() { ... }
    access(all) fun bar() {
        self.foo()
    }
}
```

2023-05-02 14:16 UTC, dsainati1 commented on cadence/2022-12-14-auth-remodel.md
> +An entitlement list defined using a `,` functions like a conjunction set (or an "and"); it is accessible only to an `auth` reference with all of those entitlements.
I will specify this in the FLIP directly, but the reason there's no note on precedence for these operators here is because you cannot mix them: for simplicity's sake an entitlements set can either be a disjunction or a conjunction, but not both. This is both a simplification for the users (especially because the actual use case for a mixed set would be very rare) and also on the implementation side (since we won't need to implement a full-on boolean algebra solver to decide entitlement relations. 

As for `+`, I think this would be confusing, since `+` often means "or" in other languages, especially those with algebraic types, where the "sum" type represents the union/disjunction between two types and the "product" type represents the intersection/conjunction.

2023-05-02 14:18 UTC, dsainati1 commented on cadence/2022-12-14-auth-remodel.md
> +that the access rules defined above allow any `access(I)` members to be accessed on it.
Yeah, I was planning on adding the new modifiers to the table in the docs here: https://developers.flow.com/cadence/language/access-control

Agree though that this information can be presented more concisely in a table here though, so I'll add it.

2023-05-02 14:21 UTC, dsainati1 commented on cadence/2022-12-14-auth-remodel.md
> +the owner of the inner resource.
I believe @SupunS was looking into potentially adding entitlement support for using entitlements to handle mutability on built in container types. I am in favor of adding these, but IMO we shouldn't expand the scope of this particular FLIP any further than it's already grown. These can be proposed in a follow-up FLIP that expands upon the existing entitlements to add them to containers.

2023-05-02 14:22 UTC, dsainati1 commented on cadence/2022-12-14-auth-remodel.md
> +```
Agree 100%. I'll update the examples in the FLIP, but IMO a proposal to remove and replace `pub` and `priv` deserves its own FLIP.

2023-05-02 14:37 UTC, dsainati1 commented on cadence/2022-12-14-auth-remodel.md
> +```
I've updated this to use a more standard implementation for nested objects using accessor functions. As for the motivation, I think the `AuthAccount` use case does use reference-typed members, and is sufficiently motivating in that sense.

2023-05-02 20:43 UTC, dete commented on cadence/2022-12-14-auth-remodel.md
> +```
Can we talk live about this? One of the big motivations for the mapping feature was to make using the composition pattern much smoother in Cadence. If a Resource that contains a Resource can only grant access to the inner Resource via a method call, I feel like we're falling short. Maybe it's a future enhancement tho?

2023-05-02 21:11 UTC, turbolent commented on cadence/2022-12-14-auth-remodel.md
> +```
This was discussed as part of the "external mutability" discussions we have recently. There, one idea was that field access on owned fields keeps resulting in the owned type (in `typeFun`, `self.inner` has type  `@SomeType`), as it does currently, but external field access on references results in a reference (in `test`, `r.inner` has type `&SomeType`).

Agreed that it might be better to discuss this topic separately from this FLIP.

2023-05-02 21:15 UTC, turbolent commented on cadence/2022-12-14-auth-remodel.md
> +the owner of the inner resource.
Same as above: using entitlements to address the "external mutability" problem is a great idea, and so it proposing entitlements for built-in types.

However, such proposals should probably be done in separate FLIP(s), as this is one is already very large.

Let's continue discussing these ideas as part of the "external mutability" problem discussions.

2023-05-03 20:39 UTC, bjartek reviewed
I have been busy so have not had time to look at this or follow this much at all. 

Is cadence supposed to be simple and readable? 

Some of these advanced entitlement mapping are not simple and not easy to understand. What is the added benefit here? I really second what @dete is saying here in that we need practical examples not abstract ones.

2023-05-03 20:39 UTC, bjartek commented on cadence/2022-12-14-auth-remodel.md
> +An entitlement list defined using a `,` functions like a conjunction set (or an "and"); it is accessible only to an `auth` reference with all of those entitlements.
Personally i feel that || and && are more natural operators to use.

2023-05-03 20:46 UTC, dsainati1 commented
I completely agree when the purpose of these examples is to teach users how the language works and tutorialize the new features for new users. When we write the documentation for entitlements, we should make sure that the examples we use are relevant to the kind of code smart contract developers actually write. We will also need to update the existing Cadence tutorial to use the new entitlements in their implementation, which I think will go a long way towards making this example simple and comprehensible to people.

However, the purpose of this FLIP is not to explain how this feature is going to work for users, and should not be used as reference documentation after the feature is deployed. The FLIP is a reference document for the designers and implementors of the language, and needs to be precise and detailed in its language, and simple in its examples so that people who are debating the design and implementation of the feature have all the information they need to make decisions. This means that the FLIP is necessarily going to be more complex and more abstract than the actual documentation will be, and I wouldn't use this FLIP as a basis for what the documentation will look like when it's finished.

2023-05-05 18:39 UTC, austinkline commented
Hi everyone! Apologies as well for only just not commenting on this FLIP, I'll try to make a note to come back to these more often in the future but it has been hard to keep track of them lately. I wanted to summarize some points after our breakout session for Hybrid Custody Wednesday and a Design meeting yesterday (Thursday), and share some thoughts that I'm hoping we can clarify a path for so that the Hybrid Custody initiative can continue uninterrupted

1. It was mentioned that Capabilities might be broken with this change and in that case would have to be reissued by the Account they belong to
2. Entitlements could alter what an AuthAccount is which means stored types which use it could break. For instance, the working hybrid custody contract is storing the following type: `Capability<&AuthAccount>`, this type could become invalid.
3. On the release of Entitlements, functions with the `pub` access modifier would be accessible to anyone with a reference to any restricted type of that object, existing assumptions on access control won't be true, and some functions will be vulnerable on existing deployed contracts

Some thoughts:

### Breaking Capabilities

Breaking Capabilities isn't really an option, not just for Hybrid Custody but for lots of products out there which store capabilities which they are not able to reissue. For instance, if we broken capabilities, all storefront listings across all products (TopShot, All Day, Flowty, Gaia, Find) would all break and only users would be able to fix them.

In general, I do not think we can consider any change which will break existing Capabilities. Cap Cons has an edge case I think we can live with (if at the time of migration, the capability's link is not valid, it will not be valid), but my understanding on Entitlements after hearing information about it in our calls this week is that they would all be invalid. It sounds like this is a tradeoff to prevent malicious access of public function modifiers but please correct me if I'm wrong.

Let's assume breaking capabilities is not an option, here. What other ways are there to handle this migration? I've seen it mentioned that you could make all capabilities that currently exist into `auth` capabilities but that seems like it would leak access to things we don't want folks to be able to reach. Is there anything else on that front which has been discussed?

### AuthAccount type definitions

Account linking has been out for a while at this point (a month?). If we change the type definition of Accounts such that `AuthAccount` is not valid anymore, then all existing contracts which store this type like HybridCustody will break permanently (we cannot update existing type definitions)

What is the plan to move forward, there? What I don't want is a world where we have to pause all of our Hybrid Custody work because changes like this are in-flight. It could be months before this/stable cadence are out so waiting on them isn't a great option for us. Daniel mentioned some ability to make a type alias to keep AuthAccount for legacy reasons such as what I'm describing here, is that the plan? And if not, how would transaction prepare statements have to change and what's the plan to get all transactions updated? Especially for Dapper Wallet, that will be a huge challenge.

### Pub access modifier

Based on the last two meetings described earlier, any functions with the `pub` access modifier would be callable by any borrowed reference to an underlying resource with entitlements, regardless of its restricted types. In the long-term, that is probably fine, but what is the path to get there? In my mind, even a single block where someone can submit a transaction with public access to something a contract didn't intent to expose is not acceptable. Is there a way to roll that specific piece of functionality out over time?

@bluesign mentioned the following in the [hybrid custody discord channel](https://discord.com/channels/613813861610684416/1104044158609530964/1104050667695382560) as an option:
- Deprecate pub
- introduce entitlements and treat pub as some entitlement ( pub becomes access(pub) instead of access(all) ) 
- remove pub

---------

We don't want to throw a huge wrench in Entitlements or Hybrid Custody, and we also want to make sure that other products not related to either initiative don't break irreparably when this feature goes out. What would make the most sense in terms of tackling these challenges? We mentioned a breakout session in our last call, can we start there?

We're trying pretty hard to keep momentum on the Hybrid Custody front, so the more momentum we can maintain there the better

2023-05-05 19:09 UTC, dsainati1 commented
Thanks for your thoughts @austinkline, these are great. I'll address them in reverse order (from least to most complex).

> Pub access modifier

I just published https://github.com/onflow/flips/pull/84, which proposes that we remove the `pub` (and `priv`) access modifiers from the language, requiring users to use the long form `access(all)` and `access(self)`. This would take effect with the release of Stable Cadence, essentially requiring that all contracts need to be updated to conform to the new Stable Cadence changes before they can be used again, and there would not be any block where data is unduly exposed to attack that was previously safe. 

> AuthAccount type definitions

Based on what you've outlined here I think it makes sense to leave `&AuthAccount` as an existing type alias for the fully entitled `&Account` reference, and `&PublicAccount` as a type alias for the unentitled reference. This would maintain the old behavior (i.e. you are able to do everything on an account or nothing), but if users want more granular control (e.g. only publishing new contracts and nothing else) they would need to use the new entitlements feature. We should include this in the FLIP for AuthAccount Capabilities when it gets published (@turbolent). 

> Breaking Capabilities

In the above point, we would be able to define `&AuthAccount` to be a fully entitled reference to `Account` for 2 reasons:

1. The binary nature of the authorization as explained above, either you have full permission or you don't. There are no existing account references that have a partial authorization to the account. 

2. We would know a priori what all the possible entitlements on an `Account` will be, because we control the Account type, and thus can create an alias `&AuthAccount = auth(ContractUpdate, ContractAdd, KeyAdd, ... etc) &Account` since we know all the possible entitlements that an account would need.

These two assumptions do not hold in general, which is what makes it very complicated to figure out how to migrate an existing `Capability<&{X}>` reference. In the old old model of entitlements, when entitlements were interfaces, we could transform any reference `&{X}` into an `auth(X) &{X}`, as this would let the reference call all the functions on `X` but not anything more, which matches the old behavior of restricted types. However, now that entitlements are independent of interfaces, this isn't possible just from inspecting the type syntactically. 

We are going to have a breakout session to discuss this further (please attend if you are interested in this topic!), because I agree that we can't just break all existing capabilities, so we need to come up with a migration strategy. One potential option would be to allow contract upgrades to be scheduled in advance, and use the entitlements added in those prescheduled upgrades to give us the answer to point 2 above, which would allow us to migrate references of type `&{X}` to `auth(E1, E2, ...) &{X}`, where `E1` through `En` would be all the entitlements that exist on `X`. However as you point out this relies on developers getting the upgrade "right" on the first try, which may be an unrealistic assumption to make.

2023-05-05 22:07 UTC, bjartek commented
> I just published #84, which proposes that we remove the `pub` (and `priv`) access modifiers from the language, requiring users to use the long form `access(all)` and `access(self)`. This would take effect with the release of Stable Cadence, essentially requiring that all contracts need to be updated to conform to the new Stable Cadence changes before they can be used again, and there would not be any block where data is unduly exposed to attack that was previously safe.

When is entitlements comming out then? Because that cannot happen at the same time as this. One has to come first to make people safe and then we can fix things with entitlments later. We have to do this in multiple steps even though i hate breaking backwards compatability often. 

So in my eyes it looks like stable cadence will have to atleast be a double rocket. First we launch prelimiary changes, everybody have to fix things, then we do another change and people have to fix again and then we are flying to the moon?

2023-05-05 22:27 UTC, dsainati1 commented
@bjartek Changing `pub` to `access(all)` does not inherently make a contract safer, the two mean the same thing one is just an alias for the other. The benefit of packaging this change with entitlements is that it will essentially break all contracts. Then, when entitlements are rolled out as part of Stable Cadence, all these contracts that become unsafe will also stop type checking, making them uninteractable until they are updated to fix the new type errors (and also to use entitlements, hence making them safe again).

2023-05-05 22:35 UTC, bjartek commented
> @bjartek Changing `pub` to `access(all)` does not inherently make a contract safer, the two mean the same thing one is just an alias for the other. The benefit of packaging this change with entitlements is that it will essentially break all contracts. Then, when entitlements are rolled out as part of Stable Cadence, all these contracts that become unsafe will also stop type checking, making them uninteractable until they are updated to fix the new type errors (and also to use entitlements, hence making them safe again).

Ok, that is better then them working and beeing exploitable atleast.

2023-05-05 23:36 UTC, turbolent commented
@austinkline Thank you for the great feedback, questions, and concerns! We will work through these points in the coming weeks. 

In the meantime, please do not consider this FLIP or the current lack of answers for your points be any blocker for any work that you have in progress.

2023-05-08 18:47 UTC, austinkline commented
> @austinkline Thank you for the great feedback, questions, and concerns! We will work through these points in the coming weeks.
> 
> In the meantime, please do not consider this FLIP or the current lack of answers for your points be any blocker for any work that you have in progress.

Thanks @turbolent and @dsainati1! I'll keep an eye out for follow-up discussion. Please feel free to loop me in if I can assist in any way

2023-05-09 16:54 UTC, SupunS reviewed
Just a couple of minor nits:

2023-05-09 16:54 UTC, SupunS commented on cadence/2022-12-14-auth-remodel.md
> +### Entitlement-access fields
Though the title says "Entitlement-access fields", the section describes only about functions.
Maybe make the title generic, and also add an example of how fields would work.

2023-05-09 16:54 UTC, SupunS commented on cadence/2022-12-14-auth-remodel.md
> +or someone with an `auth(X)` reference to the type on which the member is defined. The `X` here can be the qualified name of any entitlement, e.g.:
Here the paragraph use notation `X` for entitlement (e.g: `access(X)`), but the example below uses `E` (e.g: `access(E)`). Would be good to use the same notations for the arbitrary names, everywhere

2023-05-16 22:11 UTC, turbolent commented on cadence/2022-12-14-auth-remodel.md
> +flip: NNN (do not set)
```suggestion
flip: 54
```

2023-05-16 22:11 UTC, turbolent commented on cadence/2022-12-14-auth-remodel.md
> +# Entitlements
```suggestion
# FLIP 54: Entitlements
```

2023-05-16 22:11 UTC, turbolent commented on cadence/2022-12-14-auth-remodel.md
file name should be `20221214-...`

2023-05-23 21:20 UTC, turbolent approved these changes
🚀

2023-05-23 23:29 UTC, merged