FLIP - Interaction Templates v1.1.0
onflow/flips pull request #77
Opened 2023-03-31 22:17 UTC by JeffreyDoyle

# FLIP - Interaction Templates v1.1.0

## Overview

This update to the InteractionTemplate and InteractionTemplateInterface data structures is the result of the need to better define the order of various properties of the InteractionTemplate and InteractionTemplateInterface, for use during the serialization process required for ID generation. 

This change uses JSON lists to express the order of certain elements of the InteractionTemplate and InteractionTemplateInterface, instead of Objects as we're previously used which do not have a notion of order.

## Required updates

- [ ] FCL Interaction Template utils updated to support v1.1.0 of InteractionTemplate and InteractionTemplateInterface
- [ ] FCL Query/Mutate updated to support v1.1.0 of InteractionTemplate
- [ ] [FLIX Interaction Templates](https://github.com/onflow/flow-interaction-template-service) migrated to version v1.1.0 
- [ ] [Interaction Template Tools](https://github.com/onflow/flow-interaction-template-tools) (CLI, WebApp and JS Utils) updated to support version v1.1.0

2023-04-04 20:05 UTC, bjartek commented
Should we consider changing the way pins are generated as well here to be debth first since we are creating a new version?

I think the pin should be sha3(your_code, sha3(dep1), sha3(dep2)) or something like that so if you have done sha3(dep1) you can memoize that for all FLIX. Or even cache it.

2023-05-23 14:12 UTC, sideninja commented
@m-Peter I think this could be an improvement to an existing solution that is currently lacking. The way I see is we have to solve this problem for any transaction or script, then after we solve the mapping we can improve the mapping for flix templates by integrating into flix. I don't see the other way around to be better.

2023-08-08 16:20 UTC, bthaile commented
Support new import syntax: In order to be consistent across all flow tools, it would be beneficial for flix to support new import syntax. This syntax does not have a contract address placeholder in the cadence code. It uses `import "ContractName"` which is interpreted by flow tools. The change needed is in the "dependencies" section, the contract address placeholder isn't needed. See below:

Pervious version:
```
dependencies: {
      "0xFUNGIBLETOKENADDRESS": { // Network (mainnet || testnet) dependent locations for 0xFUNGIBLETOKENADDRESS contract.
          "FungibleToken" : {
              mainnet: {
                  address: "0xf233dcee88fe0abe", // Address of the account the contract is located.
                  fq_address: "A.0xf233dcee88fe0abe.FungibleToken", // Fully qualified contract identifier.
                  pin: "asdfasdfasdfasdfasdfasdfsadf123123123123", // Unique identifier of the interactions dependency tree.
                  pin_block_height: 10123123123 // Block height the pin was generated against.
              },
              testnet: {
                  address: "0x9a0766d93b6608b7",
                  fq_address: "A.0x9a0766d93b6608b7.FungibleToken",
                  pin: "asdfasdfasdfasdfasdfasdfsadf123123123123",
                  pin_block_height: 10123123123
              }
          }
      }
  },
```

New version:
```
dependencies: {
    "FungibleToken" : {
        mainnet: {
            address: "0xf233dcee88fe0abe", // Address of the account the contract is located.
            fq_address: "A.0xf233dcee88fe0abe.FungibleToken", // Fully qualified contract identifier.
            pin: "asdfasdfasdfasdfasdfasdfsadf123123123123", // Unique identifier of the interactions dependency tree.
            pin_block_height: 10123123123 // Block height the pin was generated against.
        },
        testnet: {
            address: "0x9a0766d93b6608b7",
            fq_address: "A.0x9a0766d93b6608b7.FungibleToken",
            pin: "asdfasdfasdfasdfasdfasdfsadf123123123123",
            pin_block_height: 10123123123
        }
    }
},
```

2023-08-08 19:55 UTC, bthaile commented on flips/20230330-interaction-templates-1.1.0.md
> +```javascript
Changed the example to be depth first

2023-08-14 17:25 UTC, bthaile commented
todo: change "argument(s)" to "parameter(s)"

2023-08-14 18:01 UTC, JeffreyDoyle reviewed
Updates according to feedback from the Interaction Template working group on August 14 2023

2023-08-23 10:04 UTC, bjartek requested changes

2023-08-23 10:04 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +function processContract(contract) {
I think there is a problem with this psudo code, when recalculating a pin for a single chaged contract this leads to a lot on unneccesary work. 

Lets take the ExampleNFT in the flow-nft repo as an example. It has the following hirarchy
```
ExampleNFT
 - NonFungibleToken
 - MetadataViews
  - FungibleToken
  - NonFungibleToken
 - ViewResolver
```
With the current algorithm if ExampleNFT changes you have to nest all the way down into the dependencies of MetadataViews to calculate the pin. 

What i propose instead is a recursive algorithm like this:
 ```

 function generateDependentPin(service, contract, contracts) {
    // Generate pin for self if not already generated
    if (!contract.selfPin) {
        contract.selfPin = shaHex(contract.body);
    }

    // Initialize an array to store pins
    const pins = [contract.selfPin];

    // Iterate through each import (dependency) in the imports list of the current contract
    for (const imp of contract.imports) {
        // Recursively generate dependent pins for the imported contract
        const depPins = generateDependentPin(service, imp, contracts);
        // Append the dependent pins to the pins array
        pins.push(...depPins);
    }

    // Calculate a pin for the current contract by applying the shaHex function to the concatenated pins
    contract.pin = shaHex(pins.join(''));

    // Add the updated contract to the contracts object using its key
    contracts[contract.contractKey()] = contract;

    // Return the array of pins
    return pins;
}

```

The main difference here is that once you have calculated the pin for a contract and its dependencies that contract can be reused until it changes.

2023-08-23 10:40 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +function processContract(contract) {
the algorithm above needs to first delete the pin of a changed contract before that code is called.

2023-08-24 08:20 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +function processContract(contract) {
I have now implemented this, this is an example row of how this works for a niftory based NFT

```{"pin": "7701e8bd1d17f32498edcced9afa7dfa5cd198be40c2c7c993897569261746dd", "pinParts": ["e788e78352b04a38495cef43bab10e1d7ddf8d6ba0af86cdf36c6381c29ed934", "b2ab6c499be905685f1b34cfd0e6fb5740be90421589a9a230bc6b193d813b74", "d0605dd3cc79f9c0c8e68dbda9e18f7ef57302ab1fac83481b5c9817dcabb1b7", "db3aef2f72d1096cb7f9ddcaad0c6692d770bda92fa4c202675d01d18abeb6fd", "16811e966e5ec36cc9df7aeb15e10ff58b82e18c63f57dabc5a452201d4089f6", "d816a566ae515d0bc5845fef8fb937bbb80315346aff9af6173f877e942da7ea", "38dcd652b06d634678bc0d009e28f1b7c149bcd503f1cad652fad65b0b54c495", "63c334bcdbad3b4b28a3843a11ab22ba1d36f141f978f1d80e5a7c6e4bd32f81", "40575f755c046e2851c8b97e8fcf31b0f3deb185f941063dc59960aec0210f6f", "5ff238dd74d2a80a28314f494ee17e11a4b56c0cd038309c3e8858d6e8c41cb9", "cf8a66a03aff94024434bf67a35143820db62e7faf5fd0529709f2310904764b", "987952d0f5aeaece55159bb059a80a4bae11abffc464e142c635fc8081f67b30", "ce611f41a7261389215901bcfa4871de4c8bfdbbf88e8d033e6e3b763e442433"], "contract": "A.2772aa34edded534.rojanscontract", "pinSource": ["A.2772aa34edded534.rojanscontract", "A.1d7e57aa55817448.NonFungibleToken", "A.1d7e57aa55817448.MetadataViews", "A.1d7e57aa55817448.ViewResolver", "A.7ec1f607f0872a9e.MutableMetadata", "A.7ec1f607f0872a9e.MutableMetadataTemplate", "A.7ec1f607f0872a9e.MutableMetadataSet", "A.7ec1f607f0872a9e.MutableMetadataSetManager", "A.7ec1f607f0872a9e.MetadataViewsManager", "A.7ec1f607f0872a9e.NiftoryNonFungibleToken", "A.7ec1f607f0872a9e.NiftoryNFTRegistry", "A.7ec1f607f0872a9e.NiftoryMetadataViewsResolvers", "A.7ec1f607f0872a9e.NiftoryNonFungibleTokenProxy"], "selfPin": "e788e78352b04a38495cef43bab10e1d7ddf8d6ba0af86cdf36c6381c29ed934"}
```

2023-08-24 08:22 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +function processContract(contract) {
Currently only the selfPin and pin are saved here, we do not save the pinParts or pinSource. note that order of pinParts/pinSource is the order of the imports in the file, that is why i did not make it a map, because order does matter here.

2023-08-30 19:40 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +function processContract(contract) {
psudo javascript code
```javascript
function generateDependentPin(contractKey, contracts) {
    const contract = contracts[contractKey];

    if (contract.Pin !== '') {
        return contract.Pin;
    }

    contract.SelfPin = shaHex(contract.Body);

    const pins = [contract.SelfPin];
    for (const imp of contract.Imports) {
        const dep = generateDependentPin(imp.ContractKey(), contracts);
        pins.push(dep);
    }

    contract.Pin = shaHex(pins.join(''));
    return contract.Pin;
}

// Example contracts map
const contracts = {
    contract1: {
        Body: '...',
        Imports: [...],
        Pin: '',
        SelfPin: ''
    },
    contract2: {
        Body: '...',
        Imports: [...],
        Pin: '',
        SelfPin: ''
    },
    // ... more contracts ...
};

// Compute pins for each contract
for (const contractKey in contracts) {
    generateDependentPin(contractKey, contracts);
}
```

2023-10-17 11:47 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +For example, different marketplaces may have different mechanics behind how a user may "List" their asset on them, but across all implementations, the action "List" is what they all aim to do.
While i def see the end goal here, I think that ITI (InteractionTemplateInterfaces) are less usefull the the templates themselves. 

Because a lot different vendors will have diferent parameters to the same "type" of Action. Some marketplaces needs a storefrontAddress for instance to list while others do not. 

It does not hurt to have it here, but I dont see it beeing used very much unfortunately

2023-10-17 11:47 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +    import "FlowToken"
In this example we use the new format of imports, but I am not sure that is what the flixkit uses currently? I think this new format is the way to go personally.

2023-10-17 11:47 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +        balance: "FungibleToken" // The token this parameter acts upon.
This should be a fully qualified identifier to the token IMHO, or can it be? If this is not network specific it cant be.

2023-10-17 11:47 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +    import "FlowToken"
This should import FungibleToken to be correct and not FlowToken?

2023-10-17 11:47 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +                  imports: [
Do we really need dependencies of dependencies here infinitely added? Is it not enough to have 1 level of direct imports and their pins?

2023-10-17 11:47 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +function processContract(contract) {
Can we take a look at my alternate suggestion here? it really scales tons better.

2023-10-17 11:47 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +#### Interaction Template Discovery
I think this sections needs more fleshing out. In order for this solution to be really used by devs we need to standardize this a little more I think. Atleast provide a reference implementation on how to do the correct thing. So lets say i develop a contract put it on testnet and publish some templates. IMHO that should be as easy as doing

2023-10-17 11:53 UTC, bjartek requested changes

2023-10-17 11:53 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +### Interaction Template Audits
Are we trying to do to much in 1 flip here? A lot of these 2. day operations needs some more experimentation with the core flix before we really know how to make a workflow that works and scales for everybody.

2023-10-17 11:53 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +### FCL Integration
Should we mention flixkit and the bindings here?

2023-11-02 17:34 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +                dependency_pin_block_height: 10123123123 // Block height the pin was generated against.
body_hash: hex.EncodeToString(sha256.Sum256(<resolved cadence>)

2023-11-02 17:37 UTC, bthaile commented on protocol/20230330-interaction-templates-1.1.0.md
> +                dependency_pin_block_height: 10123123123 // Block height the pin was generated against.
"body_hash" is confusing since the fully population transaction code would having fully qualified imports. 
maybe a other name would be better, "fully_qualified_hash"

2023-11-06 21:38 UTC, bthaile commented on protocol/20230330-interaction-templates-1.1.0.md
> +                      imports: []
Seems having an imports inside imports is over kill since the `pin` should have all the information needed.

2023-11-06 21:39 UTC, bthaile commented on protocol/20230330-interaction-templates-1.1.0.md
> +                  imports: [
I agree, will remove the second layer of `imports[]`

2023-11-09 18:44 UTC, bthaile commented on protocol/20230330-interaction-templates-1.1.0.md
> +                dependency_pin_block_height: 10123123123 // Block height the pin was generated against.
Let's call it `cadence_hash` using sha256.

2023-11-09 18:51 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +    cadence: // Cadence code this interaction executes.
TODO:

Add cadence hashes feature here as decided in FLIX working group:

```javascript
// Top Level
...
"cadence": {
  "body": "...."
  "pins": [
    {
      "network": "mainnet",
      "pin": "abc123"
    },
    {
      "network": "testnet",
      "pin": "def456"
    }
  ]
}
...
```

This also needs to be added to the serialization spec.

2023-11-09 18:52 UTC, JeffreyDoyle reviewed
Adding comments from working group Nov 9

2023-11-14 17:32 UTC, JeffreyDoyle commented
Hello all!

As per the FLIX Working Group's previous meeting on November 9th 2023, the group has aligned on the following updates to the FLIX specification to be included in version 1.1:

- Add support for the "new import syntax" in the cadence included in the Interaction Template 
- Add the full dependency tree inside the Interaction Template's dependency section.
- Use the depth first search algorithm proposed by @bjartek for computing dependency pins (see: https://github.com/onflow/flips/pull/77#discussion_r1302790294)
- Include hashes of the cadence included in the Interaction Template resolved per each supported network.

The following updates are reflected in the FLIP as of the date of this comment (Nov 14 2023). Please let us know if you have any thoughts or feedback!

-- 

If you're not in the FLIX working group and would like to be, please feel free to send an email to wallet-wg@flow.com and we will include you in the following meeting invites! 😄

2023-11-14 18:43 UTC, bjartek requested changes

2023-11-14 18:43 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +        balance: "FungibleToken" // The token this parameter acts upon.
```suggestion
        balance: "FlowToken" // The token this parameter acts upon.
```

2023-11-14 18:43 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +                translation: "Amount of FLOW token to transfer", // Messages might consume parameters.
This is wrong?

2023-11-14 18:43 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +              translation: "Amount of FLOW token to transfer",
This is wrong?

2023-11-14 18:43 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +  let contract_code = getContract(contract)
this pseudo code is still not debt first is it?

2023-11-14 18:43 UTC, bjartek commented on protocol/20230330-interaction-templates-1.1.0.md
> +#### Arbitrary Execution Phase
I honestly think that this FLIP covers so much and that this should be left for later.

2023-11-14 20:20 UTC, wfalcon0x commented on protocol/20230330-interaction-templates-1.1.0.md
> +          pin: "186e262ce6fe06b5075ec6569a0e5482a79c471881182612d8e4a665c2977f3e"
In my opinion
`hash: "186e262ce6fe06b5075ec6569a0e5482a79c471881182612d8e4a665c2977f3e"`
could better describe what the value is.
The array is called `pins: [` , so users would understand each item in the collection describes a pin.

2023-11-14 20:23 UTC, wfalcon0x commented on protocol/20230330-interaction-templates-1.1.0.md
> +            networks: [
Using `pins: [` instead of `networks: [` would make it consistent with the naming in the cadence object.

2023-11-14 20:23 UTC, wfalcon0x commented on protocol/20230330-interaction-templates-1.1.0.md
> +                  pin: "c8cb7cc7a1c2a329de65d83455016bc3a9b53f9668c74ef555032804bac0b25b", // Unique identifier of this contract dependency and it's dependency tree.
In my opinion
hash: "c8cb7cc7a1c2a329de65d83455016bc3a9b53f9668c74ef555032804bac0b25b"
could better describe what the value is. See above...

2023-11-14 20:24 UTC, wfalcon0x commented on protocol/20230330-interaction-templates-1.1.0.md
> +                  pin_self: "38d0cca4b74c4e88213df636b4cfc2eb6e86fd8b2b84579d3b9bffab3e0b1fcb", // Unique identifier of this dependency
In my opinion
hash_self: "38d0cca4b74c4e88213df636b4cfc2eb6e86fd8b2b84579d3b9bffab3e0b1fcb"
could better describe what the value is. See above...

2023-11-14 20:26 UTC, wfalcon0x commented on protocol/20230330-interaction-templates-1.1.0.md
> +                  pin_contract_name: "FlowToken",
As the object is already called `dependency_pin: {` above, it is sufficient to call this value just `contract_name`

2023-11-14 20:26 UTC, wfalcon0x commented on protocol/20230330-interaction-templates-1.1.0.md
> +                  pin_contract_address: "0x1654653399040a61",
As the object is already called `dependency_pin: {` above, it is sufficient to call this value just `contract_address`

2023-11-14 21:09 UTC, wfalcon0x commented on protocol/20230330-interaction-templates-1.1.0.md
> +        balance: "FungibleToken" // The token this parameter acts upon.
I think it should be fully qualified identifier, as it is possible to create any contract with the same name under a different account. It would mean this value needs to have separate value for the different networks.

2023-11-20 21:31 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +template-cadence-networks     = [
```suggestion

template-cadence-body-resolved   =  The cadence body for the transaction/script with imports resolved for the given network
cadence-pins-network.                     =  The network name for this pin ("mainnet" | "testnet" | "emulator")
cadence-pins-pin                               =  sha3_256(template-cadence-body-resolved )

template-cadence-networks     = [
  sha3_256(cadence-pins-network), 
  cadence-pins-pin,
]

template-cadence-body          = The body of the cadence transaction or script with string imports

template-cadence-content      =  [
  sha3_256(template-cadence-body ),
  [...template-cadence-networks]
]

```

2023-11-20 21:32 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +### `InteractionTemplate` f_version 2.0.0
```suggestion
### `InteractionTemplate` f_version 1.1.0
```

2023-11-21 17:53 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +                  imports: [
Having all of the dependencies directly in the Interaction Template will help wallets identify, if it recomputes an Interaction Template's dependency pin and it doesn't match what's in the Interaction Template, which dependencies in the tree changed to cause the discrepancy.

2023-11-21 17:53 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +            translation: "Get FLOW Balane"
```suggestion
            translation: "Get FLOW Balance"
```

2023-11-21 19:29 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +function processContract(contract) {
Implemented in the FLIP!

2023-11-21 19:30 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +For example, different marketplaces may have different mechanics behind how a user may "List" their asset on them, but across all implementations, the action "List" is what they all aim to do.
Todo: Address Interaction Template Interface in further working group convos

2023-11-21 19:37 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +        balance: "FungibleToken" // The token this parameter acts upon.
Implemented in the FLIP

2023-11-21 19:39 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +#### Interaction Template Discovery
Per FLIX working group: Let's leave updating this section for a future discussion

2023-11-21 19:40 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +### Interaction Template Audits
Per FLIX working group: Let's work on this in a future discussion.

2023-11-21 19:41 UTC, JeffreyDoyle commented on protocol/20230330-interaction-templates-1.1.0.md
> +#### Arbitrary Execution Phase
Per FLIX working group: Let's work on this in a future discussion.

2023-11-22 16:29 UTC, bthaile approved these changes
congrates, looks good

2023-11-22 19:38 UTC, gregsantos approved these changes
lg2G

2023-11-28 18:28 UTC, merged